# scrollnag
complete -f -c scrollnag
complete -c scrollnag -s C -l config -r --description 'The config file to use. Default: $HOME/.scrollnag/config, $XDG_CONFIG_HOME/scrollnag/config, and SYSCONFDIR/scrollnag/config.'
complete -c scrollnag -s d -l debug --description 'Enable debugging.'
complete -c scrollnag -s e -l edge -fr --description 'Set the edge to use: top or bottom'
complete -c scrollnag -s f -l font -r --description 'Set the font to use.'
complete -c scrollnag -s h -l help --description 'Show help message and quit.'
complete -c scrollnag -s b -l button -fr --description 'Create a button with a text and an action which is executed when pressed. Multiple buttons can be defined by providing the flag multiple times.'
complete -c scrollnag -s l -l detailed-message --description 'Read a detailed message from stdin. A button to toggle details will be added. Details are shown in a scrollable multi-line text area.'
complete -c scrollnag -s L -l detailed-button -fr --description 'Set the text for the button that toggles details. This has no effect if there is not a detailed message. The default is "Toggle details".'
complete -c scrollnag -s m -l message -fr --description 'Set the message text.'
complete -c scrollnag -s o -l output -fr --description 'Set the output to use.'
complete -c scrollnag -s s -l dismiss-button -fr --description 'Sets the text for the dismiss nagbar button. The default is "X".'
complete -c scrollnag -s t -l type -fr --description 'Set the message type. Two types are created by default "error" and "warning". Custom types can be defined in the config file.'
complete -c scrollnag -s v -l version --description 'Show the version number and quit.'

# Appearance
complete -c scrollnag -l background -fr --description 'Set the color of the background.'
complete -c scrollnag -l border -fr --description 'Set the color of the border.'
complete -c scrollnag -l border-bottom -fr --description 'Set the color of the bottom border.'
complete -c scrollnag -l button-background -fr --description 'Set the color for the background for buttons.'
complete -c scrollnag -l text -fr --description 'Set the text color.'
complete -c scrollnag -l border-bottom-size -fr --description 'Set the thickness of the bottom border.'
complete -c scrollnag -l message-padding -fr --description 'Set the padding for the message.'
complete -c scrollnag -l details-border-size -fr --description 'Set the thickness for the details border.'
complete -c scrollnag -l button-border-size -fr --description 'Set the thickness for the button border.'
complete -c scrollnag -l button-gap -fr --description 'Set the size of the gap between buttons.'
complete -c scrollnag -l button-dismiss-gap -fr --description 'Set the size of the gap between the dismiss button and another button.'
complete -c scrollnag -l button-margin-right -fr --description 'Set the margin from the right of the dismiss button to edge.'
complete -c scrollnag -l button-padding -fr --description 'Set the padding for the button text.'
